Comments and minor improvements for utils.ts
cashubtc/cashu-ts pull request #83
Opened 2023-09-06 09:19 UTC by vnnkl

Added some comments to the function to make them more consistent with the others

The `isObj` function in the `utils.ts` file has been updated to provide more accurate type checking. Instead of simply checking if the value is an object, it now checks if it is an object with a string key and unknown value. This change improves the reliability of type checking in the codebase because in TypeScript, null is considered an object, which can lead to unexpected behavior.

Made checkResponseError more concise

2023-09-12 21:32 UTC, callebtc approved these changes

2023-09-19 08:23 UTC, gandlafbtc requested changes
Thanks for the PR!

Sorry i got to it so late. 

We removed axios, do you want to adapt the PR? 
I think you can remove the changes in the `checkResponseError` function. No need to change anything there, we want to revamp the error handling anyway

2023-12-08 04:20 UTC, gandlafbtc reviewed
Hi! Can you please add the missing return types? I think then after this we merge it. I'm still waiting on feedback on other PRs, but IDK how long this takes, so let's merge this first

2023-12-08 04:20 UTC, gandlafbtc commented on src/utils.ts
>  function isPowerOfTwo(number: number) {
while we're at it, can you add the return type to this function signature?

2023-12-08 04:20 UTC, gandlafbtc commented on src/utils.ts
>  export function deriveKeysetId(keys: MintKeys) {
Can you add the missing return type here?

2023-12-08 04:20 UTC, gandlafbtc commented on src/utils.ts
>  export function sortProofsById(proofs: Array<Proof>) {
and here

2024-11-16 08:51 UTC, gandlafbtc commented
closing due to inactivity

2024-11-16 08:51 UTC, closed without merging